// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RockId.Qarp.DataMapper.Repositories;

namespace RockId.Qarp.DataMapper.Migrations
{
    [DbContext(typeof(RockIdQarpContext))]
    [Migration("20190402195922_MergedChangesToStable")]
    partial class MergedChangesToStable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RockId.Qarp.DataMapper.Models.Qarp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateUtc");

                    b.Property<string>("CreatedBy");

                    b.Property<int>("DisplayOrder");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsQuestion");

                    b.Property<int?>("ParentId");

                    b.Property<string>("RockType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdateDateUtc");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Qarps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(4624),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "What is the grain size?",
                            IsQuestion = true,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(5328),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6039),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "Glassy (no visible grains)",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6044),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6050),
                            CreatedBy = "System",
                            DisplayOrder = 2,
                            DisplayText = "Fine Grained (not easy to see grains)",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6050),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6051),
                            CreatedBy = "System",
                            DisplayOrder = 3,
                            DisplayText = "Mixed Fine and Coarse",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6052),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6053),
                            CreatedBy = "System",
                            DisplayOrder = 4,
                            DisplayText = "Medium to Coarse",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6053),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6054),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "Is it light or dark?",
                            IsQuestion = true,
                            ParentId = 2,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6054),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6135),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "Light - Quartz",
                            IsQuestion = false,
                            ParentId = 6,
                            RockType = "Igneous",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6136),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6137),
                            CreatedBy = "System",
                            DisplayOrder = 2,
                            DisplayText = "Dark - Obsidian",
                            IsQuestion = false,
                            ParentId = 6,
                            RockType = "Igneous",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 59, 21, 798, DateTimeKind.Utc).AddTicks(6137),
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
