// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RockId.Qarp.DataMapper.Repositories;

namespace RockId.Qarp.DataMapper.Migrations
{
    [DbContext(typeof(RockIdQarpContext))]
    [Migration("20190402191947_AddedUpdatableAndMoreQarpData")]
    partial class AddedUpdatableAndMoreQarpData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RockId.Qarp.DataMapper.Models.Qarps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateUtc");

                    b.Property<string>("CreatedBy");

                    b.Property<int>("DisplayOrder");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsQuestion");

                    b.Property<int?>("ParentId");

                    b.Property<string>("RockType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdateDateUtc");

                    b.Property<string>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Qarps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(8238),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "What is the grain size?",
                            IsQuestion = true,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(8943),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9653),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "Glassy (no visible grains)",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9658),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9664),
                            CreatedBy = "System",
                            DisplayOrder = 2,
                            DisplayText = "Fine Grained (not easy to see grains)",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9664),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9665),
                            CreatedBy = "System",
                            DisplayOrder = 3,
                            DisplayText = "Mixed Fine and Coarse",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9666),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9666),
                            CreatedBy = "System",
                            DisplayOrder = 4,
                            DisplayText = "Medium to Coarse",
                            IsQuestion = false,
                            ParentId = 1,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9667),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9668),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "Is it light or dark?",
                            IsQuestion = true,
                            ParentId = 2,
                            RockType = "NA",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9668),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9669),
                            CreatedBy = "System",
                            DisplayOrder = 1,
                            DisplayText = "Light - Quartz",
                            IsQuestion = false,
                            ParentId = 6,
                            RockType = "Igneous",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9669),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9670),
                            CreatedBy = "System",
                            DisplayOrder = 2,
                            DisplayText = "Dark - Obsidian",
                            IsQuestion = false,
                            ParentId = 6,
                            RockType = "Igneous",
                            UpdateDateUtc = new DateTime(2019, 4, 2, 19, 19, 46, 966, DateTimeKind.Utc).AddTicks(9670),
                            UpdatedBy = "System"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
