// <auto-generated />
using System;
using EventLogger.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventLogger.Migrations
{
    [DbContext(typeof(EventLoggerContext))]
    [Migration("20190122210435_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventLogger.Model.RockIdEvent", b =>
                {
                    b.Property<int>("RockIdEventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EventDateTimeUTC");

                    b.Property<string>("EventSource");

                    b.Property<string>("EventTitle");

                    b.Property<string>("User");

                    b.HasKey("RockIdEventId");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
