[environments]
  [environments.development]
    name = "api-qarp"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    override-ports = ["8100:8100"]    
