[environments]
  [environments.development]
    name = "gateway-spa"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    override-ports = ["90:90"]
