version: '3'

services:
  mssql-server-linux:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    networks: 
      - rockid-network      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks: 
      - rockid-network

  qarp:
    image: erniep888/qarpglassyrock:latest    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8100          
    networks: 
      - rockid-network

  rockid-bff-spa:
    image: erniep888/rockid-bff-spa:latest    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:90          
    ports:
      - "90:90"      
    networks: 
      - rockid-network

networks: 
  rockid-network:
    driver: bridge          