version: '3'

services:
  qarp:
    build:
      context: ./Service/Qarp/Qarp.GlassyRock/
      dockerfile: Dockerfile
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    
  rockid-bff-spa:
    build:
      context: ./ApiGateway/BackendForFrontend_Spa/
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
