[environments]
  [environments.development]
    name = "ui-spa-ng"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    override-ports = ["4200:4200"]  
